name: Test AtlasCLI Action
on:
  push:
jobs:
  no-version:
    name: Use AtlasCLI without version input
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI without version input
        uses: mongodb/atlas-github-action@main
  input-version:
    name: Use AtlasCLI with version input
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI with version input
        uses: mongodb/atlas-github-action@main
        with:
          version: v1.9.0
