name: Test AtlasCLI Action
on:
  push:
jobs:
  no-version:
    name: Use AtlasCLI without version input
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI without version input
        uses: mongodb/atlas-github-action@main
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
  input-version:
    name: Use AtlasCLI with version input
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI with version input
        uses: mongodb/atlas-github-action@main
        with:
          version: v1.9.0
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
  create-delete-project:
    name: Create and delete project
    runs-on: ubuntu-latest
    env:
      MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
      MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }}
    steps:
      - name: Setup AtlasCLI and create a project
        id: create-project
        uses: mongodb/atlas-github-action@main
        with:
          create-project-name: ${{ github.run_id }}-project1
      - name: delete project
        uses: mongodb/atlas-github-action@main
        with:
          delete-project-id: ${{ steps.create-project.outputs.create-project-id }}
  create-delete-cluster:
    name: Create and delete cluster
    runs-on: ubuntu-latest
    env:
      MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
      MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }}
    steps:
      - name: Setup AtlasCLI and create a project
        id: create-project
        uses: mongodb/atlas-github-action@main
        with:
          create-project-name: ${{github.run_id}}-project2
      - name: Create cluster
        id: create-cluster
        uses: mongodb/atlas-github-action@main
        with:
          create-cluster-name: test-cluster
          project-id: ${{ steps.create-project.outputs.create-project-id }}
      - name: Delete cluster
        uses: mongodb/atlas-github-action@main
        with:
          delete-cluster-name: test-cluster
          project-id: ${{ steps.create-project.outputs.create-project-id }}
      - name: delete project
        uses: mongodb/atlas-github-action@main
        with:
          delete-project-id: ${{ steps.create-project.outputs.create-project-id }}
